spring:
  application:
    name: order-command-service
  data:
    mongodb:
      host: localhost
      port: 27017
      auto-index-creation: true
      database: potato
      authentication-database: admin
      username: potato
      password: test1234

# Axon Server
axon:
  axonserver:
    servers: localhost:8124
#    servers? Axon Server? ??? ? ??? ?????. ?? ??? ????? ??? ??? ??? ?????.
    snapshot-prefetch: 10
#    snapshot-prefetch? Axon Server?? ???? ???? ? ???? ?? ??? ?? ?????.
  aggregate:
    snapshot-threshold:  10
#    snapshot-threshold? ???? ???? ?? ???? ???? ? ??? ?? ??? ?? ?????.
  serializer:
    general: jackson