spring:
  application:
    name: order-command-service
  data:
    mongodb:
      host: localhost
      port: 27017
      auto-index-creation: true
      database: potato
      authentication-database: admin
      username: potato
      password: test1234

# Axon Server
axon:
  axonserver:
    servers: localhost:8124
    snapshot-prefetch: 10
  aggregate:
    snapshot-threshold:  10
  serializer:
    general: jackson